### ISSUE TITLE
Next release for Angular 5

### ISSUE THREAD

**Issue by DenisLaboureyras** [JonnyBGod/ng2-scrollspy#181]
Hello,

Do you have a deadline to publish a new version with the bug fix for Angular 5 (OpaqueToken) ? Angular 5 is in RC9 so it will be available soon.
I tried to use the master branch directly but I couldn't build the library.

Thanks a lot
Denis

**Comment by JonnyBGod** [comment]
Should be fixed now

**Comment by DenisLaboureyras** [comment]
Thanks a lot !
