### ISSUE TITLE
Angular6 ngrx6 rxjs6 compatability issues

### ISSUE THREAD

**Issue by sssalib42** [JonnyBGod/ng2-scrollspy#188]
After upgrading to rxjs 6, I can't finish my upgrade process, specifically the very last step, which is to remove the rxjs-compat library, because ngrx-scrollspy is still using rxjs5 syntax.

Here is a github issue, explaining the problem I'm facing because ngrx-scrollspy isn't up to date:
https://github.com/ReactiveX/rxjs/issues/3654

Here is a useful page including the rxjs 6 upgrade instruction: 
https://auth0.com/blog/whats-new-in-rxjs-6/

**Comment by sssalib42** [comment]
Hi guys, it has been a month so far. Will someone be looking into this soon? Please let us know.

**Comment by sssalib42** [comment]
Will someone approve my PR and complete it if I do the work? Do I need special authorization privileges to create the PR?

I want to create a PR to upgrade the repository myself to using rxjs6 as I have it done it once for our team's code base following the migration documentation:
https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md

Thanks.

**Comment by sssalib42** [comment]
Update: 
I have the code ready to create a PR. It's about time before it gets reviewed and committed. Thanks.

**Comment by JonnyBGod** [comment]
where is the PR?

**Comment by sssalib42** [comment]
I need commit privileges. Sent you a direct email.

**Comment by JonnyBGod** [comment]
Usualy you would fork the repo and then create a PR. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

But ill give you access to the main repo.

**Comment by sssalib42** [comment]
PR is ready:
https://github.com/JonnyBGod/ngx-scrollspy/pull/189
Thanks @JonnyBGod

**Comment by JonnyBGod** [comment]
Should be fix with https://github.com/JonnyBGod/ngx-scrollspy/releases/tag/v1.2.1

**Comment by JonnyBGod** [comment]
Thank you for your contribution.
