### ISSUE TITLE
 Cannot find name 'ScrollSpyModule'.

### ISSUE THREAD

**Issue by kodiraj** [JonnyBGod/ng2-scrollspy#68]
i did as per the readme text .

when i try to start using npm,i get the below error

app/app.module.ts(19,5): error TS2304: Cannot find name 'ScrollSpyModule'.

**Comment by JonnyBGod** [comment]
I just updated readme.md with proper inputs for demos. My mistake sry.

**Comment by kodiraj** [comment]
Thanks .it solved the error.But new errors pop up.

You have working version of this.?

**Comment by kodiraj** [comment]
in my app.module.ts  
import { ScrollSpyModule } from 'ng2-scrollspy';

@NgModule({
  bootstrap: [App],
  declarations: [
    App
  ],
  imports: [ // import Angular's modules
    BrowserModule,
    HttpModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    **ScrollSpyModule.forRoot(),**
    NgaModule,
    PagesModule,
    routing
  ],
  providers: [ // expose our Services and Providers into Angular's dependency injection
    ENV_PROVIDERS,
    APP_PROVIDERS
  ]
})

in my page.module.ts
import { ScrollSpyElementDirective, ScrollSpyService } from 'ng2-scrollspy';
@NgModule({
  imports: [CommonModule, NgaModule, routing],
  declarations: [Pages,ScrollSpyElementDirective]
})

in my page.componenet.ts

import { ScrollSpyElementDirective, ScrollSpyService } from 'ng2-scrollspy';

export class Pages {

 constructor(scrollSpyService: ScrollSpyService) {
        this.scrollSpyService = scrollSpyService;
    }

```
ngAfterViewInit() {
    this.scrollSpyService.getObservable('test').subscribe((e: any) => {
        console.log('ScrollSpy::test: ', e);
    });
}
```

}

when i run through npm

  [default] /Users/kodiraj/Downloads/nextgenportal1/src/app/pages/pages.component.ts:38:14 
    Property 'scrollSpyService' does not exist on type 'Pages'.
[default] /Users/kodiraj/Downloads/nextgenportal1/src/app/pages/pages.component.ts:42:14 
    Property 'scrollSpyService' does not exist on type 'Pages'.
[default] Checking finished with 5 errors

it would really help ,if you have some demo of this feature

**Comment by JonnyBGod** [comment]
in you pages.component.ts you should declare the scrollSpyService variable. One way is:

```
export class Pages {
    constructor(private scrollSpyService: ScrollSpyService) {
    }

    ngAfterViewInit() {
        this.scrollSpyService.getObservable('test').subscribe((e: any) => {
            console.log('ScrollSpy::test: ', e);
        });
    }
}
```

**Comment by kodiraj** [comment]
hi,

Can you share some demo code if possible..

**Comment by kodiraj** [comment]
hi,

i have nested components.Here how should i handle it?

**Comment by kodiraj** [comment]
scrollSpyElement=“kodiraj"

i declared the above tag in only one place.

ScrollSpy: duplicate id "kodiraj". Instance will be skipped!

But i get the error in the console.

**Comment by JonnyBGod** [comment]
Please try new version [v0.3.0](https://github.com/JonnyBGod/ng2-scrollspy/releases/tag/v0.3.0).

Make sure you read docs for new declaration system.

I will try to create more documentation and example during next week.
