### ISSUE TITLE
ScrollSpyElementDirective doesn't work

### ISSUE THREAD

**Issue by NatsuOnFire** [JonnyBGod/ng2-scrollspy#78]
Hi,
I tried to add ng2-scrollspy to [angular2 webpack starter 2.1.1](https://github.com/AngularClass/angular2-webpack-starter) project but when I want to use ScrollSpyElementDirective I am getting no console.log.

**Comment by NatsuOnFire** [comment]
Sorry, It works fine. 
I thought that the scroll on an element would act when we get to that element in the page.
I did not think it was on the scroll of that same element and it's not the same as [Waypoints](http://imakewebthings.com/waypoints/)

**Comment by JonnyBGod** [comment]
That is a good use case. It should be possible to implement with a directive. Will probably add it when I get the time.

**Comment by ValentinFunk** [comment]
I've implemented a rudimentary Waypoints script using ng2-scrollspy, for anyone who need it: https://gist.github.com/Kamshak/63661e7ea251c92364a2ed1238f04264

**Comment by JonnyBGod** [comment]
@Kamshak Cool thank you for mentioning. Would you like to turn it into a plugin to be included in this repo?

**Comment by ValentinFunk** [comment]
The code works in a basic setup but i'm not sure if it will work for nested scroll panels. There are also some features that one could add (a Z offset for detection) and scroll directions.

At the moment i can't adapt it for more cases however feel free to add it as plugin maybe it will be useful for someone. Could act as a starting point
